name: Label Automation

on:
  issues:
    types: [opened]

jobs:
  update-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout na branch
        uses: actions/checkout@v2

      - name: Instalação do Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalação das Dependências
        run: npm install

      - name: Atribuição de Label Automática
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: node ./scripts/adicionar-label.js